Lab7: main.o
	g++ -g -std=c++11 main.o -o Lab7

main.o: main.cpp Sort.h Sort.hpp BogoSort.h BogoSort.hpp BubbleSort.h BubbleSort.hpp InsertionSort.h InsertionSort.hpp MergeSort.h MergeSort.hpp QuickSort.h QuickSort.hpp
	g++ -g -std=c++11 -c main.cpp


clean:
	rm *.o Lab7

