/*	File Name: <main.cpp> 
	Author: Lacie Chavez 
        KUID: 2752051
	Email Address: l542c849@ku.edu
	Homework Assignment Number: Lab5
	Description: BST 
	Last Changed: 3/28/2014 
*/
Program: main.o
	g++ -g -std=c++11 main.o -o Program

main.o: main.cpp Node.h BinarySearchTree.h 
	g++ -g -std=c++11 -c main.cpp

clean:
	rm *.o Program
